import React from 'react';
import { X } from 'lucide-react';

interface TermsOfServiceProps {
  isOpen: boolean;
  onClose: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 shrink-0">
          <h2 className="text-lg font-black text-slate-900 uppercase tracking-wide">Terms of Service</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
            <X size={22} />
          </button>
        </div>

        {/* Scrollable body */}
        <div className="overflow-y-auto px-6 py-5 text-sm text-slate-700 space-y-6 leading-relaxed">

          <p className="text-xs text-slate-500">Effective Date: February 22, 2026 &nbsp;·&nbsp; Last Updated: February 22, 2026</p>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">1. Acceptance of Terms</h3>
            <p>
              By creating an account or using Analyze My Property ("the Service", "we", "us"), you agree to be bound by
              these Terms of Service and our Privacy Policy. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">2. Description of Service</h3>
            <p>
              Analyze My Property is a software platform that provides AI-assisted real estate underwriting and financial
              projection tools. The Service uses artificial intelligence (Anthropic Claude), third-party market data
              (RentCast), and user-provided inputs to generate property analysis reports.
            </p>
            <p className="mt-2">
              <strong>The Service is provided for informational purposes only.</strong> Nothing on this
              platform constitutes financial advice, investment advice, legal advice, or a recommendation to buy, sell,
              or hold any real estate asset or financial instrument.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">3. No Investment Advice — Important Disclaimer</h3>
            <p>
              All projections, estimates, cap rates, cash-on-cash returns, ADR figures, occupancy rates, and other
              financial metrics generated by the Service are <strong>estimates only</strong>. They are based on
              AI-generated analysis and third-party data sources that may be incomplete, outdated, or inaccurate.
            </p>
            <p className="mt-2">
              Real estate investing involves significant risk, including the possible loss of principal. Past market
              performance does not guarantee future results. You should:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>Independently verify all data before making any investment decision</li>
              <li>Consult a licensed real estate professional, financial advisor, or attorney</li>
              <li>Conduct your own due diligence, including property inspections and title searches</li>
              <li>Understand that actual results may differ materially from projected estimates</li>
            </ul>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">4. Third-Party Data</h3>
            <p>
              The Service integrates data from third-party providers including RentCast and Anthropic. This data is
              provided "as-is" without warranty of accuracy, completeness, or fitness for any particular purpose.
              We are not responsible for errors or omissions in third-party data.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">5. User Accounts</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials. You agree to notify
              us immediately of any unauthorized use of your account. You may not share your account or use the Service
              on behalf of another person without authorization.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">6. Subscription and Billing</h3>
            <p>
              Paid subscriptions are billed through Stripe. By subscribing, you authorize recurring charges at the
              stated frequency. You may cancel your subscription at any time through your account settings; access
              continues until the end of the current billing period. We do not offer refunds for partial periods unless
              required by applicable law.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">7. Acceptable Use</h3>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-slate-600">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service at scale</li>
              <li>Use automated tools to exceed your plan's analysis limits</li>
              <li>Resell or redistribute analysis outputs without permission</li>
              <li>Impersonate another person or entity</li>
            </ul>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">8. Intellectual Property</h3>
            <p>
              The Service, including its software, design, and underlying AI prompts, is owned by Analyze My Property.
              You retain ownership of any data you input into the Service. You grant us a limited license to process
              your data for the purpose of providing the Service.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">9. Limitation of Liability</h3>
            <p>
              To the maximum extent permitted by applicable law, Analyze My Property and its owners, employees, and
              agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages,
              including but not limited to investment losses, lost profits, or lost data arising from your use of or
              reliance on the Service.
            </p>
            <p className="mt-2">
              Our total liability to you for any claim arising out of or relating to the Service shall not exceed the
              amount you paid us in the three months preceding the claim.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">10. Disclaimer of Warranties</h3>
            <p>
              The Service is provided "as is" and "as available" without warranty of any kind, express or implied,
              including warranties of merchantability, fitness for a particular purpose, or non-infringement.
              We do not warrant that the Service will be uninterrupted, error-free, or completely accurate.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">11. Termination</h3>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these Terms or
              for any other reason at our discretion. You may delete your account at any time by contacting us.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">12. Governing Law and Dispute Resolution</h3>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of New York,
              without regard to its conflict of law provisions. Any disputes arising under these Terms shall be
              subject to the exclusive jurisdiction of the state and federal courts located in New York.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">13. Changes to Terms</h3>
            <p>
              We may update these Terms from time to time. We will notify you of material changes by email or by
              displaying a notice in the Service. Continued use of the Service after the effective date constitutes
              your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h3 className="font-bold text-slate-900 mb-2">14. Contact</h3>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:support@analyzemyproperty.com" className="text-[#4CAF50] hover:underline">
                support@analyzemyproperty.com
              </a>
            </p>
          </section>

        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-200 shrink-0 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 bg-slate-900 text-white text-sm font-semibold rounded-lg hover:bg-slate-700 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
